### ISSUE TITLE
Demo applications / Classic App

### ISSUE THREAD

**Issue by fntlnz** [pennyphp/discussion#3]
At the moment when we do a BC in penny (like [#102](https://github.com/pennyphp/penny/pull/102))  we have to update multiple repositiories (bookshelf, classic-app) we should consider having just one "skeleton-application" somehow complete.

Currently bookshelf is using twig + doctrine + symfony forms and other goodies.

What do you think?

**Comment by samsonasik** [comment]
classic-app for skeleton-application is ok for me, bookshelf is rather more complex case sample

**Comment by fntlnz** [comment]
Ok so we may rename classic app to something like skeleton-app ? 
What do you think about having doctrine in skeleton app?

**Comment by samsonasik** [comment]
for naming, classic-app is still ok for me, i think the skeleton should be as slim as possible without db anymore. iirc, like symfony did, probably one more repo for "demo app" will be cool, but bookshelf already demoing it, right?

**Comment by gianarb** [comment]
In my opinion penny-classic-app, bookshelf and for example twitter-uservice
https://github.com/gianarb/twitter-uservice

are only different implementation of penny.. Are 3 app.. :) We maintain classic-app and bookshelf because we are interesting to update them..

if penny-classic-app is not a good name we can change the name and we can try to design an OFFICIAL skeleton app that implements a set of libraries that we decide here.. :)

**Comment by fntlnz** [comment]
Yes you got the point. What could be a good name for the classic app?
Skeleton application? Base application?

**Comment by fntlnz** [comment]
Ok I just don't like the classic app name :D and I don't like plates as
default templating engine btw

**Comment by gianarb** [comment]
np I change it in skeleton-app

**Comment by samsonasik** [comment]
penny- prefix will be better, so penny-skeleton-app :)

**Comment by gianarb** [comment]
ok :)

**Comment by fntlnz** [comment]
:+1:

**Comment by gianarb** [comment]
Done.
We start another issue into the correct repo to choose the best components for our skeleton app :)

Thanks!
